server:
  port: 0 # 랜덤 포트

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true # 웹 접속 허용
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

eureka:
  client:
#    Eureka server 등록
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # micro service가 등록된 server 위치
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    같은 이름의 MSA 구분하여 등록

greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.inflearn.userservice: DEBUG

token:
  expiration_time: 86400000
  secret: user_token